### PR TITLE
Add NOTICE to binary package and fix some typo

### PR DESCRIPTION
**Pull request by hanahmily**
Signed-off-by: Gao Hongtao <hanahmily@gmail.com>

### CODE REVIEW

**Review by wu-sheng — DISMISSED** [review]

**Comment by wu-sheng** [comment]
@lujiajing1126 I think client lib should follow this fix too? Although gRPC/protobuf makes this change compatible with previous versions.

**Review by lujiajing1126 — APPROVED** [review]

**Review by wu-sheng — APPROVED** [review]

**Comment by lujiajing1126** [comment]
> @lujiajing1126 I think client lib should follow this fix too? Although gRPC/protobuf makes this change compatible with previous versions.

Java Client does not have this typo. While moving code there, I've already fixed it.

https://github.com/apache/skywalking-banyandb-java-client/blob/main/src/main/proto/banyandb/v1/banyandb-property.proto#L77

**Comment by hanahmily** [comment]
> @lujiajing1126 I think client lib should follow this fix too? Although gRPC/protobuf makes this change compatible with previous versions.

After checking the java-client's proto files, I didn't find similar types. It seems they don't affect the interoperations between client and server.

**Comment by lujiajing1126** [comment]
> > @lujiajing1126 I think client lib should follow this fix too? Although gRPC/protobuf makes this change compatible with previous versions.
> 
> After checking the java-client's proto files, I didn't find similar typo. It seems they don't affect the interoperations between client and server.

Yes. The protocol itself only cares about the position and the type of the field.

**Pull request merged**
