### PR TITLE
chore: print log code normalization

### PR DESCRIPTION
**Pull request by caicancai**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Fixes apache/skywalking#<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
@hanahmily Do we have such detailed code style check now?

**Comment by caicancai** [comment]
> @hanahmily Do we have such detailed code style check now?

Judging from the cli error, it seems that it cannot be changed in this way. Do I need to close this PR? This may be personal obsessive-compulsive disorder

**Comment by wu-sheng** [comment]
@hanahmily What does the CI error mean? It seems not related to this PR changes.

**Comment by hanahmily** [comment]
I will close it since it violates the linter rules. Please follow the `CONTRIBUTING.md` before submitting PRs.

**Pull request closed without merging**
