### PR TITLE
Update Go to 1.18

### PR DESCRIPTION
**Pull request by lujiajing1126**
Update Go to 1.18. Close https://github.com/apache/skywalking/issues/9169

Notable dependencies upgrade,

- `buf`: from 1.0.0 to 1.5.0
- `protobuf` and gen tools: from 1.17.1 to 1.18.0
- `klauspost/compress`: from 1.13.1 to 1.15.6
- `grpc` and gen tools: from 1.39.0 to 1.47.0

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please update versions of dependencies in License file.

**Comment by lujiajing1126** [comment]
> Please update versions of dependencies in License file.

You mean the LICENSE file in the `dist` folder?  I think I've already updated.

**Comment by wu-sheng** [comment]
`installation.md` is not updated to 1.18.

**Comment by lujiajing1126** [comment]
> `installation.md` is not updated to 1.18.

Thanks for reminding. Fixed now.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
