### PR TITLE
Fix topn query nil and add more context to err

### PR DESCRIPTION
**Pull request by hanahmily**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Fixes apache/skywalking#12219.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Review by lujiajing1126 — APPROVED** [review]
LGTM

**Comment by lujiajing1126** [comment]
Will we cherry-pick this commit to v0.6.x?

**Comment by wu-sheng** [comment]
> Will we cherry-pick this commit to v0.6.x?

It depends on why this happens. If this is blocking the general use, we should have 0.6.1. Otherwise, it is not in urgent. 
e2e covers the feature, but it doesn't complain anything.

@lujiajing1126 Do you face anything in testing?

**Comment by hanahmily** [comment]
> Will we cherry-pick this commit to v0.6.x?

I prefer waiting for 24 hours for future feedback on the error, and regardless of the result, a new patch is necessary.

**Comment by Almot77** [comment]
Okay, i'l test it now.

We use php application in docker + sw php libay for trace collecting + grafana dashboards (made from sw examples for grafana)

**Pull request merged**
