### PR TITLE
fix: some links are broken in the doc

### PR DESCRIPTION
**Pull request by LinuxSuRen**
- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Fixes apache/skywalking#<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you refer main repo to add dead link check?

**Comment by LinuxSuRen** [comment]
> Could you refer main repo to add dead link check?

Sure

**Comment by LinuxSuRen** [comment]
There is an image URL is broken. Is there anyone know it?

FILE: ./docs/concept/persistence-storage.md
  [✖] https://skywalking.apache.org/doc-graph/banyandb/v0.5.0/io_uring.png

**Comment by wu-sheng** [comment]
> There is an image URL is broken. Is there anyone know it?
> 
> FILE: ./docs/concept/persistence-storage.md [✖] https://skywalking.apache.org/doc-graph/banyandb/v0.5.0/io_uring.png

It is a jpg. Ref URL, https://skywalking.apache.org/doc-graph/banyandb/v0.5.0/io_uring.jpg

The original file is hosted here, https://github.com/apache/skywalking-website/blob/master/static/doc-graph/banyandb/v0.5.0/io_uring.jpg

**Comment by hanahmily** [comment]
It's nice to see the dead link checker work as expected.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
