### PR TITLE
Fix integration test's leaked goroutines

### PR DESCRIPTION
**Pull request by mikechengwei**
Fixes https://github.com/apache/skywalking/issues/9957.

Signed-off-by: mikechengwei [842725815@qq.com](mailto:842725815@qq.com)

### CODE REVIEW

**Review by hanahmily — CHANGES_REQUESTED** [review]
Please fix all sub-packages in the integration test. https://github.com/apache/skywalking/issues/9957 contains three sub-tasks that need to be fixed.

**Comment by mikechengwei** [comment]
> Please fix all sub-packages in the integration test. [apache/skywalking#9957](https://github.com/apache/skywalking/issues/9957) contains three sub-tasks that need to be fixed.

The other packages just contain `suite_test` file , do you mean these file ?

**Comment by hanahmily** [comment]
> > Please fix all sub-packages in the integration test. [apache/skywalking#9957](https://github.com/apache/skywalking/issues/9957) contains three sub-tasks that need to be fixed.
> 
> The other packages just contain `suite_test` file , do you mean these file ?

Yep. Add leaking check to `SynchronizedBeforeSuite` and `SynchronizedAfterSuite` in `query` and `cold`.`load` seems to keep failure recently. You could leave it as before.

**Comment by mikechengwei** [comment]
This pr needs to wait for https://github.com/apache/skywalking-banyandb/pull/236 to combine, relying on the code of https://github.com/apache/skywalking-banyandb/pull/236, I have tested it.

**Comment by mikechengwei** [comment]
@hanahmily please help me review this pr again, thanks.

**Review by hanahmily — APPROVED** [review]
LGTM

**Pull request merged**
