### PR TITLE
Fix duplicate type names in proto

### PR DESCRIPTION
**Pull request by lujiajing1126**
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>

image

### CODE REVIEW

**Comment by wu-sheng** [comment]
Renaming is not the key. Add namespace and java package option.
Take a reference from SkyWalking protocol repository.

**Comment by lujiajing1126** [comment]
> Renaming is not the key. Add namespace and java package option.
> Take a reference from SkyWalking protocol repository.

Sorry, I am confused. I suppose the conflict is due to the duplicated name for both Enum and Message defined in the `schema.proto`.

**Comment by wu-sheng** [comment]
You said in Java, different proto files could have different Java package name, which could avoid this conflicts. 
Duplicate names are common, SkyWalking network proto could conflict with each other or banyandb too.

**Comment by lujiajing1126** [comment]
> You said in Java, different proto files could have different Java package name, which could avoid this conflicts.
> Duplicate names are common, SkyWalking network proto could conflict with each other or banyandb too.

image

Emmm, but they are in the same file?

**Comment by wu-sheng** [comment]
Same name? How go compiling passed? This seems not working in any language.

**Comment by lujiajing1126** [comment]
> Same name? How go compiling passed? This seems not working in any language.

Seems strange, the compiler automatically adds prefixes to the enum values,

image

**Comment by wu-sheng** [comment]
OK, and rename title and make change log corret.
Fix duplicate type names in proto.

**Comment by lujiajing1126** [comment]
> OK, and rename title and make change log corret.
> Fix duplicate type names in proto.

Done.

**Review by hanahmily — APPROVED** [review]
It looks like only Go, protobuf native language, doesn't have this issue 😅

**Comment by wu-sheng** [comment]
> It looks like only Go, protobuf native language, doesn't have this issue 😅

It is only go generator unreasonable fix. Like many go tools do.

**Pull request merged**
