### PR TITLE
Index `measure_name` and `tags` in `entity` to improve the query performance.

### PR DESCRIPTION
**Pull request by hanahmily**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Fixes apache/skywalking#12877.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
This should improve the `mode=index` measure query performance, right?

**Comment by wu-sheng** [comment]
And it doesn't impact the other normal measure data.

**Comment by hanahmily** [comment]
> This should improve the `mode=index` measure query performance, right?

Yep. It doesn't impact other measures

**Review by wu-sheng — APPROVED** [review]
Does this improve enough to show benefits on demo.s.a.o? If so, we should consider redeploying?

**Pull request merged**
