### PR TITLE
Changes Of Issue #9759

### PR DESCRIPTION
**Pull request by DevPJ9**
Added "In" and "Not_In" parsers in index_filter.go

### CODE REVIEW

**Comment by hanahmily** [comment]
It looks good to me. But you have to format your codes before pushing.

After committing your local changes, please issue `make pre-push` as mentioned in https://github.com/apache/skywalking-banyandb/blob/main/CONTRIBUTING.md#test-your-changes-before-pushing

**Comment by DevPJ9** [comment]
> 

I am using windows environment. Can I do the required steps in it as well? I checked the installation steps for banyanDb and there was only linux or mac were mentioned.

**Comment by hanahmily** [comment]
> > 
> 
> 
> 
> I am using windows environment. Can I do the required steps in it as well? I checked the installation steps for banyanDb and only linux or mac were mentioned there.

WSL2 is a better solution for Windows. 

If it is not the case, 'make format' and 'make lint' are the minimal requirements. They're based on pure go tools.

**Comment by DevPJ9** [comment]
> make lint' are the minimal requirements. They're based on pure go tools.

I am not sure how to execute these commands and where to. I tried to execute the commands on cmd, powershell and even on git bash. I have installed go as well but the commands are not working. I am doing it wrong. Can you please guide me through the steps.

**Comment by hanahmily** [comment]
> I am not sure how to execute these commands and where to. I tried to execute the commands on cmd, powershell and even on git bash. I have installed go as well but the commands are not working. I am doing it wrong. Can you please guide me through the steps.

It seems that you're new to Makefile. On Windows, you have to install a tool to run `make xxx` tasks. There are some [options](https://stackoverflow.com/questions/2532234/how-to-run-a-makefile-in-windows) for you.

I highly recommend you run these commands in a Ubuntu 20.x, either [WSL](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview) or [a virtual machine](https://ubuntu.com/tutorials/how-to-run-ubuntu-desktop-on-a-virtual-machine-using-virtualbox#1-overview)

**Comment by Superskyyy** [comment]
I also recommend using WSL but more times with simpler make commands you can just use Scoop to install make and it works like a charm.

**Comment by DevPJ9** [comment]
Thanks, @hanahmily @Superskyyy for your suggestions. I was overwhelmed with these many options and finally decided to install Ubuntu in VirtualBox. I am currently trying to run the make commands there. It is throwing some errors while running "make build". I will try some more, and if I cannot execute it, I will let you know. Thanks a lot for your suggestions and support.

**Comment by DevPJ9** [comment]
Hey @hanahmily @Superskyyy `PRJ was unexpected at this time.
make: *** [Makefile:142: default] Error 255` this is the error which I am getting while using make commands. I am using chocolatey right now.

**Comment by hanahmily** [comment]
> Author

There is a bash script at https://github.com/apache/skywalking-banyandb/blob/main/Makefile#L142, which doesn't work in Windows' CMD. You could run tasks in a subfolder `make -C pkg xx`

**Comment by DevPJ9** [comment]
@hanahmily 
`E:\Development_Java\OS\skywalking-banyandb>make -C pkg xx
make: Entering directory 'E:/Development_Java/OS/skywalking-banyandb/pkg'
process_begin: CreateProcess(NULL, git describe --tags --long, ...) failed.
../scripts/build/base.mk:33: pipe: No error
process_begin: CreateProcess(NULL, git rev-parse --abbrev-ref HEAD, ...) failed.
../scripts/build/base.mk:34: pipe: No error
make: *** No rule to make target 'xx'.  Stop.
make: Leaving directory 'E:/Development_Java/OS/skywalking-banyandb/pkg'`

This is the error it is throwing.

**Comment by hanahmily** [comment]
> 

`xx` represents `lint`, `format` and etc

**Comment by DevPJ9** [comment]
@hanahmily 
`make: Entering directory 'E:/Development_Java/OS/skywalking-banyandb/pkg'
process_begin: CreateProcess(NULL, git describe --tags --long, ...) failed.
../scripts/build/base.mk:33: pipe: No error
process_begin: CreateProcess(NULL, git rev-parse --abbrev-ref HEAD, ...) failed.
../scripts/build/base.mk:34: pipe: No error
'GOBIN' is not recognized as an internal or external command,
operable program or batch file.
make: *** [E:/Development_Java/OS/skywalking-banyandb/scripts/build/lint-bin.mk:4: E:/Development_Java/OS/skywalking-banyandb/scripts/build/../../bin/golangci-lint] Error 1
make: Leaving directory 'E:/Development_Java/OS/skywalking-banyandb/pkg'`

does git have anything to do with this?

**Comment by hanahmily** [comment]
> @hanahmily I tried for `E:\Development_Java\OS\skywalking-banyandb>make -C pkg format` and `E:\Development_Java\OS\skywalking-banyandb>make -C pkg lint` as well and the error is :
> 
> `make: Entering directory 'E:/Development_Java/OS/skywalking-banyandb/pkg' process_begin: CreateProcess(NULL, git describe --tags --long, ...) failed. ../scripts/build/base.mk:33: pipe: No error process_begin: CreateProcess(NULL, git rev-parse --abbrev-ref HEAD, ...) failed. ../scripts/build/base.mk:34: pipe: No error 'GOBIN' is not recognized as an internal or external command, operable program or batch file. make: *** [E:/Development_Java/OS/skywalking-banyandb/scripts/build/lint-bin.mk:4: E:/Development_Java/OS/skywalking-banyandb/scripts/build/../../bin/golangci-lint] Error 1 make: Leaving directory 'E:/Development_Java/OS/skywalking-banyandb/pkg'`
> 
> does git have anything to do with this?



> @hanahmily I tried for `E:\Development_Java\OS\skywalking-banyandb>make -C pkg format` and `E:\Development_Java\OS\skywalking-banyandb>make -C pkg lint` as well and the error is :
> 
> `make: Entering directory 'E:/Development_Java/OS/skywalking-banyandb/pkg' process_begin: CreateProcess(NULL, git describe --tags --long, ...) failed. ../scripts/build/base.mk:33: pipe: No error process_begin: CreateProcess(NULL, git rev-parse --abbrev-ref HEAD, ...) failed. ../scripts/build/base.mk:34: pipe: No error 'GOBIN' is not recognized as an internal or external command, operable program or batch file. make: *** [E:/Development_Java/OS/skywalking-banyandb/scripts/build/lint-bin.mk:4: E:/Development_Java/OS/skywalking-banyandb/scripts/build/../../bin/golangci-lint] Error 1 make: Leaving directory 'E:/Development_Java/OS/skywalking-banyandb/pkg'`
> 
> does git have anything to do with this?

It needs git command available. Would you please join our slack channel through https://skywalking.apache.org/. I help you with it more conveniently.

**Comment by wu-sheng** [comment]
You don't have to reopen another PR.

**Comment by DevPJ9** [comment]
Ok. How should I proceed now?

**Comment by wu-sheng** [comment]
For now, you keep staying on the new one. And keep all discussions on it for the future.

**Comment by DevPJ9** [comment]
Ok. Thanks.

**Pull request closed without merging**
