### PR TITLE
Fix make generate

### PR DESCRIPTION
**Pull request by tisonkun**
Otherwise, failed with:

```
--- banyand: generate ---
prog.go:12:2: missing go.sum entry for module providing package github.com/golang/mock/mockgen/model; to add:
	go mod download github.com/golang/mock
prog.go:12:2: missing go.sum entry for module providing package github.com/golang/mock/mockgen/model; to add:
	go mod download github.com/golang/mock
prog.go:14:2: no required module provides package github.com/apache/skywalking-banyandb/pkg/bus: go.mod file not found in current directory or any parent directory; see 'go help modules'
prog.go:12:2: no required module provides package github.com/golang/mock/mockgen/model: go.mod file not found in current directory or any parent directory; see 'go help modules'
2023/08/22 10:51:37 Loading input failed: exit status 1
queue/queue.go:29: running "mockgen": exit status 1
make[1]: *** [generate] Error 1
make: *** [default] Error 1
```

See also https://github.com/golang/mock/issues/494

### CODE REVIEW

**Comment by wu-sheng** [comment]
My local `make generate` passed on M1 Max. How to reproduce your error?

**Comment by tisonkun** [comment]
@wu-sheng what version of Golang you use? I do:

```
➜  skywalking-banyandb git:(main) git pull
Already up to date.
➜  skywalking-banyandb git:(main) make check-req
/Users/tison/Brittani/skywalking-banyandb/scripts/build/../../bin/ginkgo -v  -tags "" ./...
=== RUN   TestGoVersion
--- PASS: TestGoVersion (0.02s)
PASS

Ginkgo ran 1 suite in 913.153417ms
Test Suite Passed
npm install 

up to date, audited 133 packages in 1s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  skywalking-banyandb git:(main) make generate
--- api: generate ---
--- ui: generate ---
npm install 

up to date, audited 133 packages in 1s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
--- banyand: generate ---
prog.go:12:2: missing go.sum entry for module providing package github.com/golang/mock/mockgen/model; to add:
	go mod download github.com/golang/mock
prog.go:12:2: missing go.sum entry for module providing package github.com/golang/mock/mockgen/model; to add:
	go mod download github.com/golang/mock
prog.go:14:2: no required module provides package github.com/apache/skywalking-banyandb/pkg/bus: go.mod file not found in current directory or any parent directory; see 'go help modules'
prog.go:12:2: no required module provides package github.com/golang/mock/mockgen/model: go.mod file not found in current directory or any parent directory; see 'go help modules'
2023/08/22 11:16:40 Loading input failed: exit status 1
queue/queue.go:29: running "mockgen": exit status 1
make[1]: *** [generate] Error 1
make: *** [default] Error 1
```

```
$ go version
go version go1.20.6 darwin/arm64
```

**Comment by tisonkun** [comment]
It should have been fine without this patch. But perhaps the module path difference between forks can mislead

**Comment by wu-sheng** [comment]
I am using `go version go1.20.5 darwin/arm64`

**Comment by tisonkun** [comment]
After a `git clean -fdX .` it can work now.

**Pull request closed without merging**
