### PR TITLE
[OSPP] Submitted the delta and cumulative API design plan,

### PR DESCRIPTION
**Pull request by sumingfirst**
which has passed the  make -C api lint check

- [ ] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Fixes apache/skywalking#<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please fix the check.

**Comment by wu-sheng** [comment]
I think this should be for 0.8 rather than the current iteration? @hanahmily

**Comment by hanahmily** [comment]
> I think this should be for 0.8 rather than the current iteration? @hanahmily

This change is part of a long-term plan, so we are not assigning it to any specific milestone.

**Comment by wu-sheng** [comment]
But we will need to merge it at some points. I want to confirm whether it impact the compatibility of client and DB server internal.

**Review by hanahmily — APPROVED** [review]

**Comment by hanahmily** [comment]
> But we will need to merge it at some points. I want to confirm whether it impact the compatibility of client and DB server internal.

No it won't break anything. We can merge it safely.

**Pull request merged**
