### PR TITLE
Fix metrics system typo

### PR DESCRIPTION
**Pull request by sollhui**
- [x] If this pull request closes/resolves/fixes an existing issue, replace the issue number. Fixes apache/skywalking#<issue number>.
- [ ] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by wu-sheng** [comment]
I think you should update the dashboard setup(Grafana) accordingly?

**Comment by wu-sheng** [comment]
Also, changelog should be updated for 0.8.

FYI 0.7 is on the vote, this typo fix could be in 0.8-dev directly.

**Comment by sollhui** [comment]
> dashboard

This typo only involves the code level and does not require any modifications to the dashboard.

**Comment by wu-sheng** [comment]
OK, please update the changelog.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
