### PR TITLE
Move legacy implementations to v1 packages

### PR DESCRIPTION
**Pull request by lujiajing1126**
In order to simplify the PR #49 , we are going to separate it to some sub-task.

This PR intends to move all legacy implementations to v1 package to remove noise in PR #49.

@hanahmily

### CODE REVIEW

**Comment by hanahmily** [comment]
https://github.com/apache/skywalking-banyandb/pull/52 might fix test issues, would you sync it to check?

**Comment by lujiajing1126** [comment]
> #52 might fix test issues, would you sync it to check?

I would sync after merge

**Comment by lujiajing1126** [comment]
@hanahmily Merge #52 . Now all tests have passed.

**Review by hanahmily — APPROVED** [review]
Lgtm

**Pull request merged**
