### PR TITLE
Update go 1.19

### PR DESCRIPTION
**Pull request by lujiajing1126**
## Lint issues

Several lint errors occur after upgrading to go 1.19

- Package comments missing: https://tip.golang.org/doc/go1.19#go-doc
- Migrate `github.com/golang/protobuf/jsonpb` -> `google.golang.org/protobuf/encoding/protojson`
- fully deprecate `io/ioutil`

### CODE REVIEW

**Comment by hanahmily** [comment]
Why are a number of headers updated?

**Comment by lujiajing1126** [comment]
> Why are a number of headers updated?

According to the release note, 

```
Doc Comments
Go 1.19 adds support for links, lists, and clearer headings in doc comments. 
As part of this change, [gofmt](https://tip.golang.org/cmd/gofmt) now reformats doc comments to make their rendered meaning clearer. 
See “[Go Doc Comments](https://tip.golang.org/doc/comment)” for syntax details and descriptions of common mistakes now highlighted by gofmt. 
As another part of this change, the new package [go/doc/comment](https://tip.golang.org/pkg/go/doc/comment/) provides parsing and reformatting of doc comments as well as support for rendering them to HTML, Markdown, and text.
```

**Comment by hanahmily** [comment]
> > Why are a number of headers updated?
> 
> According to the release note,
> 
> ```
> Doc Comments
> Go 1.19 adds support for links, lists, and clearer headings in doc comments. 
> As part of this change, [gofmt](https://tip.golang.org/cmd/gofmt) now reformats doc comments to make their rendered meaning clearer. 
> See “[Go Doc Comments](https://tip.golang.org/doc/comment)” for syntax details and descriptions of common mistakes now highlighted by gofmt. 
> As another part of this change, the new package [go/doc/comment](https://tip.golang.org/pkg/go/doc/comment/) provides parsing and reformatting of doc comments as well as support for rendering them to HTML, Markdown, and text.
> ```

I mean that the headers are generated by skywalking-eye based on `.licenserc.yaml`. I don't see that this template is updated accordingly.

**Comment by lujiajing1126** [comment]
> I mean that the headers are generated by skywalking-eye based on `.licenserc.yaml`. I don't see that this template is updated accordingly.

Yes, previously the `gofmt` does not care the [Doc Comment](https://go.dev/doc/comment) above the package. But from the latest version, go introduces support for links, lists, and clearer headings in doc comments. 

Thus `gofmt` will reformat the Doc Comment including the License part.

According to the document,

```
/*
Gofmt formats Go programs.
It uses tabs for indentation and blanks for alignment.
Alignment assumes that an editor is using a fixed-width font.

Without an explicit path, it processes the standard input. Given a file,
it operates on that file; given a directory, it operates on all .go files in
that directory, recursively. (Files starting with a period are ignored.)
By default, gofmt prints the reformatted sources to standard output.

Usage:

    gofmt [flags] [path ...]

The flags are:

    -d
        Do not print reformatted sources to standard output.
        If a file's formatting is different than gofmt's, print diffs
        to standard output.
    -w
        Do not print reformatted sources to standard output.
        If a file's formatting is different from gofmt's, overwrite it
        with gofmt's version. If an error occurred during overwriting,
        the original file is restored from an automatic backup.

When gofmt reads from standard input, it accepts either a full Go program
or a program fragment. A program fragment must be a syntactically
valid declaration list, statement list, or expression. When formatting
such a fragment, gofmt preserves leading indentation as well as leading
and trailing spaces, so that individual sections of a Go program can be
formatted by piping them through gofmt.
*/
package main
```

It will use tabs for indentation. I suppose that is the reason why the license headers have been reformatted.

**Review by hanahmily — APPROVED** [review]
LGTM

**Pull request merged**
