### PR TITLE
Parse string and int array in the query result table

### PR DESCRIPTION
**Pull request by Fine0830**
- [x] Closes apache/skywalking#12857.
- [x] Update the [`CHANGES` log](https://github.com/apache/skywalking-banyandb/blob/main/CHANGES.md).

View string and int array in the query result table. And fix style.

Signed-off-by: Qiuxia Fan <qiuxiafan@apache.org>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Could you post a demo video?

**Comment by Fine0830** [comment]
> Could you post a demo video?

There is no array data in the demo env. Need @hanahmily to add array data.

**Comment by wu-sheng** [comment]
I think segment(stream) should have?

**Comment by Fine0830** [comment]
> I think segment(stream) should have?

It seems that there is no array data either.

**Comment by wu-sheng** [comment]
@hanahmily could you mock some data?

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
