### PR TITLE
Unify query planner and executor

### PR DESCRIPTION
**Pull request by zesiar0**
related issue https://github.com/apache/skywalking/issues/10562.

### CODE REVIEW

**Comment by lujiajing1126** [comment]
Pls fix CI first @zesiar0

**Review by hanahmily — CHANGES_REQUESTED** [review]
IIUC, the https://github.com/apache/skywalking/issues/10562 tends to merge TopN and Measure's query process. (@lujiajing1126 feel free to correct me)

However, the current implementation introduces a new analyzer. Although the new topn analyzer takes inspiration from the measure analyzer, it is not heading in the right direction.

**Comment by hanahmily** [comment]
@zesiar0 Could you fix the test cases? The current structure has almost reached the design goals.

**Comment by zesiar0** [comment]
Compared to [5801363](https://github.com/apache/skywalking-banyandb/pull/307/commits/5801363e268199c5b00d80b842f919aff233f61f) and [f70e3ce](https://github.com/apache/skywalking-banyandb/pull/307/commits/f70e3ce8bf1a74f016e1fbea53f3f762eece192a), I just modify source code related to data query and method comments. And Test (Asia/Shanghai) job succeeds in commit [5801363](https://github.com/apache/skywalking-banyandb/pull/307/commits/5801363e268199c5b00d80b842f919aff233f61f) but failed in [f70e3ce](https://github.com/apache/skywalking-banyandb/pull/307/commits/f70e3ce8bf1a74f016e1fbea53f3f762eece192a) because of data race. So is it possible there is a bug? @hanahmily @lujiajing1126

**Pull request closed without merging**
